name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container:
      image: debian:stable-slim

    steps:
      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends git ca-certificates curl nodejs python3
          rm -rf /var/lib/apt/lists/*

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # Download Bootstrap directly into docs/vendor/bootstrap
      - name: Fetch Bootstrap
        run: |
          echo "Downloading Bootstrap..."
          [ -d vendor ] && rm -rf vendor
          mkdir vendor
          git clone --depth 1 --branch v5.3.8 https://github.com/twbs/bootstrap.git vendor
          cp --remove-destination vendor/bootstrap/dist/css/bootstrap.min.css docs/css
          cp --remove-destination vendor/bootstrap/dist/css/bootstrap.min.css.map docs/css
          cp --remove-destination vendor/bootstrap/dist/js/bootstrap.bundle.min.js docs/js
          cp --remove-destination vendor/bootstrap/dist/js/bootstrap.bundle.min.js.map docs/js

      # Cache the vendor folder for faster future runs
      - name: Cache vendor directory
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-bootstrap

      # Setup Pages (skip for local act)
      - name: Setup Pages
        if: ${{ !env.ACT }}
        uses: actions/configure-pages@v5

      # Upload the docs folder as Pages artifact
      - name: Upload artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: ${{ !env.ACT }}
        id: deployment
        uses: actions/deploy-pages@v4

      # Local preview
      - name: Preview locally
        if: ${{ env.ACT }}
        run: |
          echo "Starting local preview server at http://localhost:8000"
          cd docs
          python3 -m http.server 8000
